apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=your-registry/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[0-9a-f]{7}$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/backend:latest  # Will be updated by ArgoCD
        ports:
        - containerPort: 8000