apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: djangoapp
  # namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/niteeshchaudhary/reserichdeployment.git
    targetRevision: main
    path: k8/base/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
