apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-exec-role-binding
subjects:
  - kind: ServiceAccount
    name: argo-server  # or 'argo' if you're not sure
    namespace: argo    # or the namespace you installed Argo in
roleRef:
  kind: ClusterRole
  name: argo-exec-role
  apiGroup: rbac.authorization.k8s.io
