apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-server-exec-role
rules:
  - apiGroups: [""]
    resources: ["pods/exec", "pods", "pods/log"]
    verbs: ["get", "list", "watch", "create"]
