apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
  namespace: default
data:
  patroni.yml: |
    scope: postgres-cluster
    namespace: /db/
    name: postgres-0  # Pod name (will be updated automatically)
    
    # ETCD Configuration
    etcd:
      host: etcd-0.etcd.default.svc.cluster.local:2379,etcd-1.etcd.default.svc.cluster.local:2379,etcd-2.etcd.default.svc.cluster.local:2379
      # Ensure SSL is disabled
      ssl:
        enabled: false



    # PostgreSQL Settings
    postgresql:
      listen: 0.0.0.0:5432
      connect_address: {{ pod_ip }}:5432
      data_dir: /home/postgres/pgdata
      parameters:
        ssl: "off"
      use_pg_rewind: true
      unix_socket_directories: /var/run/postgresql
      authentication:
        replication:
          username: standby
          password: standbypassword  # Specify a replication password
        superuser:
          username: postgres
          password: {{ superuser_password }}  # Use a templated value (will be replaced in your StatefulSet)
    
    # Patroni settings
    restapi:
      listen: 0.0.0.0:8008
      connect_address: {{ pod_ip }}:8008
      authentication:
        admin:
          username: admin
          password: cola  # Admin password
    
    # Additional settings
    ttl: 30
    loop_wait: 10
    maximum_lag_on_failover: 1048576  # Adjust according to your needs
    retry_timeout: 10
