---
apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
data:
  patroni.yml: |
    scope: postgres_cluster
    namespace: /db/
    name: postgres
    restapi:
      listen: 0.0.0.0:8008
      connect_address: "{{ pod_ip }}:8008"
      authentication:
        username: patroni
        password: "restapi-password"
    etcd:
      host: "etcd-0.etcd.default.svc.cluster.local"
      port: 2379
    postgresql:
      listen: 0.0.0.0:5432
      connect_address: "{{ pod_ip }}:5432"
      data_dir: /var/lib/postgresql/data
      pg_hba:
        - host replication all 0.0.0.0/0 md5
        - host all all 0.0.0.0/0 md5
      parameters:
        max_connections: 100
        shared_buffers: 256MB
        wal_level: replica
        hot_standby: "on"
        archive_mode: "on"