apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
  namespace: default
data:
  patroni.yml: |
    scope: postgres-cluster
    namespace: default
    name: postgres-0  # Will be auto-replaced in StatefulSet

    # Use Kubernetes as DCS
    kubernetes:
      labels:
        app: patroni
      pod_ip: {{ pod_ip }}
      ports:
        postgresql: 5432
        api: 8008
      scope_label: patroni-cluster
      role_label: role
      use_endpoints: true

    # PostgreSQL settings
    postgresql:
      listen: 0.0.0.0:5432
      connect_address: {{ pod_ip }}:5432
      data_dir: /home/postgres/pgdata
      parameters:
        ssl: "off"
      use_pg_rewind: true
      unix_socket_directories: /var/run/postgresql
      authentication:
        replication:
          username: standby
          password: standbypassword
        superuser:
          username: postgres
          password: {{ superuser_password }}

    restapi:
      listen: 0.0.0.0:8008
      connect_address: {{ pod_ip }}:8008
      authentication:
        admin:
          username: admin
          password: cola

    ttl: 30
    loop_wait: 10
    maximum_lag_on_failover: 1048576
    retry_timeout: 10
