apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
  namespace: default
data:
  patroni.yml: |
    scope: postgres-cluster
    name: postgres-0

    kubernetes:
      labels:
        app: postgres
      ports:
        postgresql: 5432
        api: 8008
      scope_label: patroni-cluster
      role_label: role
      use_endpoints: true

    postgresql:
      listen: 0.0.0.0:5432
      data_dir: /home/postgres/pgdata
      parameters:
        ssl: "off"
      use_pg_rewind: true
      unix_socket_directories: /var/run/postgresql

    restapi:
      listen: 0.0.0.0:8008
      authentication:
        admin:
          username: admin
          password: cola

    ttl: 30
    loop_wait: 10
    maximum_lag_on_failover: 1048576
    retry_timeout: 10
