apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: etcd
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: bitnami/etcd:latest
        command:
        - /opt/bitnami/etcd/bin/etcd
        - "--name=$(ETCD_NAME)"
        - "--data-dir=/bitnami/etcd"
        - "--advertise-client-urls=http://$(ETCD_NAME).etcd.default.svc.cluster.local:2379"
        - "--listen-client-urls=http://0.0.0.0:2379"
        - "--initial-advertise-peer-urls=http://$(ETCD_NAME).etcd.default.svc.cluster.local:2380"
        - "--listen-peer-urls=http://0.0.0.0:2380"
        - "--initial-cluster=etcd-0=http://etcd-0.etcd.default.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd.default.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd.default.svc.cluster.local:2380"
        - "--initial-cluster-token=etcd-cluster"
        - "--initial-cluster-state=new"
        - "--enable-v2=true"
        - "--logger=zap"
        - "--log-outputs=stdout"
        - "--log-level=debug"
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: etcd-data
          mountPath: /bitnami/etcd
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
