# etcd-client-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-client-test
spec:
  template:
    spec:
      containers:
      - name: etcdctl
        image: bitnami/etcd:latest
        command: ["/bin/sh", "-c"]
        args:
        - etcdctl --endpoints=http://etcd-0.etcd.default.svc.cluster.local:2379 put /message Hello;
          etcdctl --endpoints=http://etcd-0.etcd.default.svc.cluster.local:2379 get /message
      restartPolicy: Never