# etcd-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
    nodePort: 23079
  - port: 2380
    name: peer
  selector:
    app: etcd