apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: "etcd"
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: k8sre/etcd:v3.5.7 # Updated to new etcd image
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /usr/local/bin/etcd
            - --name=$(POD_NAME)
            - --initial-advertise-peer-urls=http://$(POD_NAME).etcd.default.svc.cluster.local:2380
            - --listen-peer-urls=http://$(POD_NAME).etcd.default.svc.cluster.local:2380
            - --listen-client-urls=http://$(POD_NAME).etcd.default.svc.cluster.local:2379
            - --advertise-client-urls=http://$(POD_NAME).etcd.default.svc.cluster.local:2379
            - --initial-cluster-token=etcd-cluster-1
            - --initial-cluster=$(POD_NAME)=http://$(POD_NAME).etcd.default.svc.cluster.local:2380
            - --initial-cluster-state=new
            - --enable-v2=true
          ports:
            - containerPort: 2380
            - containerPort: 2379