# etcd-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: etcd-cluster
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: etcd