apiVersion: batch/v1
kind: Job
metadata:
  name: init-reserish-db-5
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-db
        image: localhost:5000/psqlcurl
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "Discovering current PostgreSQL master..."
            for i in 0 1 2; do
              if curl -s http://postgres-$i.db:8008 | grep -q '"role": "master"'; then
                MASTER=postgres-$i.db
                echo "Master is $MASTER"
                break
              fi
            done

            if [ -z "$MASTER" ]; then
              echo "Failed to discover master pod."
              exit 1
            fi

            echo "Checking if DB exists on $MASTER..."
            if psql -h "$MASTER" -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'reserish'" | grep -q 1; then
              echo "Database 'reserish' already exists."
            else
              echo "Creating database 'reserish'..."
              createdb -h "$MASTER" -U postgres reserish
            fi
