apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  selector:
    role: master
    cluster-name: postgres-cluster
  ports:
    - protocol: TCP
      port: 5432  
      targetPort: 5432
  clusterIP: None 
