---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - port: 5432
  clusterIP: None  # StatefulSet uses stable DNS names, so we set ClusterIP to None
  selector:
    app: postgres
