apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "db"
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: patroni
          image: flant/spilo:latest
          ports:
            - containerPort: 5432
            - containerPort: 8008
          env:
            - name: KUBERNETES_ROLE_LABEL
              value: "role"  # You can customize this
            - name: KUBERNETES_SCOPE_LABEL
              value: "cluster-name"  # Required for service selectors
            - name: KUBERNETES_LABELS
              value: '{"application": "spilo"}'  # Optional; default is fine
            # Cluster identity
            - name: SCOPE
              value: "postgres-cluster"  # Same as PATRONI_SCOPE
            - name: PATRONI_SCOPE
              value: "postgres-cluster"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            # PostgreSQL superuser credentials
            - name: PGUSER_SUPERUSER
              value: "postgres"
            - name: PGPASSWORD_SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # Patroni PostgreSQL credentials
            - name: PATRONI_POSTGRESQL_USERNAME
              value: "postgres"
            - name: PATRONI_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PATRONI_POSTGRESQL_DATABASE
              value: "reserish"

            # Patroni REST API
            - name: PATRONI_RESTAPI_PASSWORD
              value: "restapi-password"
            - name: APIPORT
              value: "8008"
            - name: RESTAPI_CONNECT_ADDRESS
              value: "$(POD_NAME).postgres.default.svc.cluster.local:8008"
            - name: ETCD_HOSTS
              value: '"etcd-0.etcd.default.svc.cluster.local:2379","etcd-1.etcd.default.svc.cluster.local:2379","etcd-2.etcd.default.svc.cluster.local:2379"'

            - name: PATRONI_SSL_MODE
              value: "disable"

          volumeMounts:
            - name: pgdata
              mountPath: /home/postgres/pgdata
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
