apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default
spec:
  serviceName: "db"
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        cluster-name: postgres-cluster   # must match KUBERNETES_SCOPE_LABEL
    spec:
      serviceAccountName: patroni
      containers:
        - name: patroni
          image: flant/spilo:latest
          ports:
            - containerPort: 5432
              name: postgresql
            - containerPort: 8008
              name: patroni-restapi
          env:
            - name: DCS_ENABLE_KUBERNETES_API
              value: "true"
            - name: KUBERNETES_ROLE_LABEL
              value: "role"
            - name: PATRONI_KUBERNETES_ROLE_LABEL
              value: "role"
            - name: KUBERNETES_SCOPE_LABEL
              value: "cluster-name"
            - name: PATRONI_KUBERNETES_SCOPE_LABEL
              value: "cluster-name"
            - name: PATRONI_KUBERNETES_LABELS
              value: '{"app": "postgres"}'
            - name: KUBERNETES_LABELS
              value: '{"app": "postgres"}'
            - name: SCOPE
              value: "postgres-cluster"
            - name: PATRONI_SCOPE
              value: "postgres-cluster"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PATRONI_LOG_LEVEL
              value: DEBUG

            # PostgreSQL superuser credentials
            - name: PGUSER_SUPERUSER
              value: "postgres"
            - name: PGPASSWORD_SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # Patroni PostgreSQL credentials
            - name: PATRONI_POSTGRESQL_USERNAME
              value: "postgres"
            - name: PATRONI_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PATRONI_POSTGRESQL_DATABASE
              value: "reserish"

            # Patroni REST API credentials
            - name: PATRONI_RESTAPI_PASSWORD
              value: "restapi-password"
            - name: APIPORT
              value: "8008"
            - name: RESTAPI_CONNECT_ADDRESS
              value: "$(POD_NAME).postgres.default.svc.cluster.local:8008"

            - name: PATRONI_SSL_MODE
              value: "disable"

          volumeMounts:
            - name: pgdata
              mountPath: /home/postgres/pgdata

  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
