---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: patroni
          image: patroni:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "reserish"
            - name: PATRONI_SCOPE
              value: "postgres_cluster"
            - name: PATRONI_RESTAPI_PASSWORD
              value: "restapi-password"
            - name: PATRONI_ETCD_HOST
              value: "etcd-0.etcd.default.svc.cluster.local"
          ports:
            - containerPort: 5432
            - containerPort: 8008  # For Patroni REST API
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: patroni-config  # This is where the ConfigMap will be mounted
              mountPath: /etc/patroni
              readOnly: true
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
  volumes:
    - name: patroni-config
      configMap:
        name: patroni-config 