---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: patroni
          image: flant/spilo:latest
          env:
            - name: SCOPE
              value: "postgres_cluster"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGUSER
              value: "postgres"
            - name: PGDATABASE
              value: "reserish"
            - name: PATRONI_SUPERUSER_USERNAME
              value: "postgres"
            - name: PATRONI_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PATRONI_REPLICATION_USERNAME
              value: "replicator"
            - name: PATRONI_REPLICATION_PASSWORD
              value: "replication-password"
            - name: PATRONI_ADMIN_USERNAME
              value: "patroni"
            - name: PATRONI_ADMIN_PASSWORD
              value: "restapi-password"
          ports:
            - containerPort: 5432
            - containerPort: 8008
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data