---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: patroni
          image: flant/spilo:latest
          env:
            - name: PATRONI_SCOPE
              value: "postgres_cluster"
            - name: PATRONI_RESTAPI_PASSWORD
              value: "restapi-password"
            - name: PATRONI_ETCD_HOST
              value: "etcd-0.etcd.default.svc.cluster.local"
            - name: PATRONI_POSTGRESQL_USERNAME
              value: "postgres"
            - name: PATRONI_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PATRONI_POSTGRESQL_DATABASE
              value: "reserish""
          ports:
            - containerPort: 5432
            - containerPort: 8008  # For Patroni REST API
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: patroni-config
              mountPath: /etc/patroni
              readOnly: true
      volumes:
        - name: patroni-config
          configMap:
            name: patroni-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi