apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend/deployment.yaml
  - celery-worker.yaml
  - postgres/pv.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - redis/pv.yaml
  - redis/pvc.yaml
  - redis/deployment.yaml