---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latex
  annotations:
    argocd-image-updater.argoproj.io/image-list: latex=localhost:5000/latex
    argocd-image-updater.argoproj.io/latex.update-strategy: latest
    argocd-image-updater.argoproj.io/latex.allow-tags: regexp:^[0-9a-f]{7}$
spec:
  replicas: 2
  selector:
    matchLabels:
      app: latex
  template:
    metadata:
      labels:
        app: latex
    spec:
      containers:
        - name: latex
          image: localhost:5000/latex
          command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8001"]
          workingDir: /app
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: media-data
              mountPath: /app/shared
      volumes:
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data-pvc
