apiVersion: apps/v1
kind: Deployment
metadata:
  name: latex
  labels:
    app: latex
  annotations:
    argocd-image-updater.argoproj.io/image-list: latex=localhost:5000/latex
    argocd-image-updater.argoproj.io/latex.update-strategy: latest
    argocd-image-updater.argoproj.io/latex.allow-tags: regexp:^[0-9a-f]{7}$
spec:
  replicas: 2
  selector:
    matchLabels:
      app: latex
  template:
    metadata:
      labels:
        app: latex
    spec:
      containers:
      - name: latex
        image: localhost:5000/latex  # Replace with actual image name if not using build
        command: [ "sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8001" ]
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: media-volume
          mountPath: /app/shared
        workingDir: /app
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: latex
spec:
  selector:
    app: latex
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
