apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-arbiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-arbiter
  template:
    metadata:
      labels:
        app: mongo-arbiter
    spec:
      containers:
        - name: mongo-arbiter
          image: mongo:6.0
          command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
          ports:
            - containerPort: 27017
      terminationGracePeriodSeconds: 10
