apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo  
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: mongo-volume
          mountPath: /app/mydb
        workingDir: /app
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: log-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
