apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-rs-init
spec:
  template:
    spec:
      containers:
        - name: mongo-rs-init
          image: mongo:latest
          command:
            - bash
            - -c
            - |
              echo "Waiting for mongo-0..."
              until mongosh --host mongo-0.mongo:27017 --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
                sleep 2
              done

              echo "Waiting for mongo-1..."
              until mongosh --host mongo-1.mongo:27017 --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
                sleep 2
              done

              echo "Waiting for mongo-arbiter..."
              until mongosh --host mongo-arbiter.mongo:27017 --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
                sleep 2
              done

              echo "All MongoDB nodes are up. Initiating replica set..."
              echo '
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "mongo-0.mongo:27017" },
                  { _id: 1, host: "mongo-1.mongo:27017" },
                  { _id: 2, host: "mongo-arbiter.mongo:27017", arbiterOnly: true }
                ]
              })
              ' | mongosh --host mongo-0.mongo:27017
      restartPolicy: Never
  backoffLimit: 4
