apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: "nkc"
  DJANGO_SECRET_KEY: "your-secret-key"
  EMAIL_HOST_PASSWORD: "ncoo avad bklm howk"
  RAZORPAY_API_KEY: "rzp_test_83EoTqYaRuuSA7"
  RAZORPAY_API_SECRET: "8V30mMAFxdlffo96Mh7r2toR"
