apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  POSTGRES_HOST: "postgres-master.default.svc.cluster.local"
  POSTGRES_USER: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "reserish"
  DATABASE_URL: "postgres://postgres:nkc@postgres:5432/reserish"  # Consider templating if secret should be injected here
  REDIS_CLUSTER: "True"
  REDIS_SESSION_URL: "redis://session-redis:6379"
  CELERY_BROKER_URL: "redis://general-redis:6379"
  CELERY_RESULT_BACKEND: "redis://general-redis:6379"
  DEBUG: "False"
  CSRF_TRUSTED_ORIGINS: "https://nkc.buzz/ https://hiresmarts.in/ https://reserishmain.nkc.buzz https://kreserishmain.nkc.buzz"
  DJANGO_ALLOWED_HOSTS: "nkc.buzz 127.0.0.1 localhost 13.234.19.252 13.232.122.71 66.179.211.82 hiresmarts.in reserishmain.nkc.buzz kreserishmain.nkc.buzz"
  DJANGO_CORS_ALLOW_ALL_ORIGINS: "True"
  USERMODEL: "backend.CustomUser"
  EMAIL_HOST_USER: "niteeshkamalchaudhary00@gmail.com"
  LATEX_SERVICE_URL: "http://latex:8001"
  MONGO_URI: "mongodb://mongo:27017"
  MONGO_DB: "reserish_logs"
