apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=localhost:5000/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[0-9a-f]{7}$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: localhost:5000/backend:latest  # Will be updated by ArgoCD
        command:
            [
              "sh", "-c",
              "python manage.py migrate && \
               python manage.py collectstatic --noinput && \
               python manage.py seed_plans && \
               python manage.py create_admin && \
               gunicorn reserish.wsgi:application --timeout 120 --workers 5 --bind 0.0.0.0:8000"
            ]
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

        volumeMounts:
            - name: media-data
              mountPath: /app/media

      volumes:
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort