apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    app: celery
  annotations:
    argocd-image-updater.argoproj.io/image-list: celery=localhost:5000/celery
    argocd-image-updater.argoproj.io/celery.update-strategy: latest
    argocd-image-updater.argoproj.io/celery.allow-tags: regexp:^[0-9a-f]{7}$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: localhost:5000/celery:latest  # Will be updated by ArgoCD
          command: ["celery", "-A", "your_project_name", "worker", "--loglevel=info"]
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: DJANGO_SETTINGS_MODULE
              value: your_project_name.settings
          volumeMounts:
            - name: shared-volume
              mountPath: /app/shared
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
