apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reserish2
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/niteeshchaudhary/reserichdeployment.git
      revision: HEAD
      directories:
      - path: overlays/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/niteeshchaudhary/reserichdeployment.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'