---
# ConfigMap for Redis
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    appendonly yes
    cluster-enabled no
    protected-mode no
    dir /data
    replica-announce-ip $(POD_IP)