---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None  # Headless service for stable network identity
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis
