apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 3  # Number of Redis instances
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 26379
              name: sentinel
          volumeMounts:
            - name: redis-data
              mountPath: /data
          args:
            - /bin/sh
            - -c
            - |
              # Start the Redis server
              redis-server /etc/redis/redis.conf --appendonly yes &
              # Start Redis Sentinel with the appropriate configuration
              redis-server /etc/redis/sentinel.conf --sentinel
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
