apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 26379
              name: sentinel
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
            - name: sentinel-config
              mountPath: /etc/redis/sentinel.conf
              subPath: sentinel.conf
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Start Redis in the background
              redis-server /etc/redis/redis.conf --daemonize yes
              # Start Sentinel in the foreground (required for Kubernetes health checks)
              redis-sentinel /etc/redis/sentinel.conf
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: sentinel-config
          configMap:
            name: sentinel-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi