---
# Redis StatefulSet with Sentinel
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
        - name: config-loader
          image: busybox:1.28
          command: ['sh', '-c', 'cp /tmp/redis.conf /etc/redis/redis.conf && cp /tmp/sentinel.conf /etc/redis/sentinel.conf']
          volumeMounts:
            - name: redis-config
              mountPath: /tmp/redis.conf
              subPath: redis.conf
            - name: sentinel-config
              mountPath: /tmp/sentinel.conf
              subPath: sentinel.conf
            - name: config
              mountPath: /etc/redis
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 26379
              name: sentinel
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Start Redis server
              redis-server /etc/redis/redis.conf &
              # Start Sentinel
              redis-sentinel /etc/redis/sentinel.conf
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: sentinel-config
          configMap:
            name: sentinel-config
        - name: config
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi