apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"        # You can set it to 1, 2, or 3 depending on your HA needs
  staleReplicaTimeout: "3"    # Time in minutes to wait before considering a replica as stale
  fromBackup: ""               # Optional: Can be used to create volumes from backup
reclaimPolicy: Retain          # Or "Delete" if you want the PV to be deleted with PVC
allowVolumeExpansion: true     # Allow resizing the volume
volumeBindingMode: Immediate 