apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-job
  namespace: otel
spec:
  schedule: "@never"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: cleanup-job-sa
          restartPolicy: Never
          containers:
            - name: cleanup
              image: bitnami/kubectl:latest
              command: ["/bin/bash", "/scripts/cleanup.sh"]
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
          volumes:
            - name: script-volume
              configMap:
                name: cleanup-script
                defaultMode: 0777
