apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collectortransform-standalone
  namespace: otel
  labels:
    app: otel-collectortransform-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collectortransform-standalone
  template:
    metadata:
      labels:
        app: otel-collectortransform-standalone
    spec:
      volumes:
        - name: otel-storage
          persistentVolumeClaim:
            claimName: otel-nfs-pvc
        - name: otel-config
          configMap:
            name: otel-collector-config
      initContainers:
        - name: mkdir
          image: busybox:1.35.0
          command:
            - sh
            - -c
            - >
              mkdir -p /data/traces /data/completed /data/pending /data/failed
          volumeMounts:
            - name: otel-storage
              mountPath: /data
      containers:
        - name: opentelemetry-collector
          image: otel/opentelemetry-collector-contrib:0.72.0
          args:
            - "--config=/etc/otel-collector-config/config.yaml"
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
          volumeMounts:
            - name: otel-storage
              mountPath: /otel-data
            - name: otel-config
              mountPath: /etc/otel-collector-config
