apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-job-sa
  namespace: otel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cleanup-job-role
  namespace: otel
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "update", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-job-binding
  namespace: otel
subjects:
  - kind: ServiceAccount
    name: cleanup-job-sa
    namespace: otel
roleRef:
  kind: Role
  name: cleanup-job-role
  apiGroup: rbac.authorization.k8s.io
