apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgres://myuser:mypassword@postgres:5432/mydb"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
      initContainers:
        - name: migrate
          image: backend-image
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000