name: Build and Push Images
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Frontend
      run: |
        docker build -t localhost:5000/frontend:$GITHUB_SHA -f frontend/Dockerfile frontend/
        docker push localhost:5000/frontend:$GITHUB_SHA
        echo "FRONTEND_IMAGE=localhost:5000/frontend:$GITHUB_SHA" >> $GITHUB_ENV

    # Similar jobs for backend and celery